Repository ZEviod/open-source-mern, pull requests merged in 2024-10, with the labels that each got.

#1 ui setup to work
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
  public/robots.txt
  src/App.js
  src/App.test.js
  src/assets/file.jpg
  src/components/About.css
  src/components/About.js
  src/components/Activities.css
  src/components/Activities.js
  src/components/Activities2.css
  src/components/Activities2.js
  src/components/Contact.css
  src/components/Contact.js
  src/components/Designs.css
  src/components/Designs.js
  src/components/Details.css
  src/components/Details.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Navbar.css
  src/components/Navbar.js
  src/index.css
  src/index.js
  src/reportWebVitals.js
  src/routes/About.js
  src/routes/Activities.js
  src/routes/Contact.js
  src/routes/Designs.js
  src/routes/Home.js
  src/setupTests.js
Labels: documentation, enhancement, hacktoberfest-accepted

#10 footer init
  src/components/Footer.css
  src/components/Footer.js
Labels: hacktoberfest-accepted, front-end

#12 Issue #5 - Contact us page created
  src/components/Contact.css
  src/components/Contact.js
Labels: hacktoberfest-accepted, front-end

#13 Akash home page UI
  public/images/heroBg.jpg
  public/index.html
  src/components/About.css
  src/components/About.js
  src/components/Activities.css
  src/components/Activities.js
  src/components/Footer.css
  src/components/Footer.js
  src/components/Navbar.css
  src/components/Navbar.js
Labels: hacktoberfest-accepted
